travis:
  alt_text:     Build Status
  scheme:       https
  url_path:     travis-ci.org
  badge_slug:   travis

coveralls:
  alt_text:     Coverage Status
  url_path:     coveralls.io/r
  badge_slug:   coveralls

gemnasium:
  alt_text:     Dependency Status
  url_path:     gemnasium.com
  badge_slug:   gemnasium

codeclimate:
  alt_text:     Code Climate
  url_path:     codeclimate.com/github
  badge_slug:   codeclimate/github

pulls:
  alt_text:     Pending Pull-Requests
  service_root: githubbadges.herokuapp.com
  url_path:     github.com
  suffix:       pulls

issues:
  alt_text:     Github Issues
  service_root: githubbadges.herokuapp.com
  url_path:     github.com
  suffix:       issues
