travis:
  alt_text:     Build Status
  scheme:       https
  url_path:     travis-ci.org
  badge_slug:   travis

travis-com:
  alt_text:     Build Status
  scheme:       https
  url_path:     travis-ci.com
  badge_slug:   travis/com

coveralls:
  alt_text:     Coverage Status
  url_path:     coveralls.io/r
  badge_slug:   coveralls

gemnasium:
  alt_text:     Dependency Status
  url_path:     gemnasium.com
  badge_slug:   gemnasium

codeclimate:
  alt_text:     Code Climate
  url_path:     codeclimate.com/github
  badge_slug:   codeclimate/github

dependencyci:
  alt_text:     Dependency CI
  service_root: dependencyci.com/github
  url_path:     github/doge
  suffix:       badge

pulls:
  alt_text:     Pending Pull-Requests
  service_root: githubbadges.herokuapp.com
  url_path:     github.com
  suffix:       pulls

issues:
  alt_text:     Github Issues
  service_root: githubbadges.herokuapp.com
  url_path:     github.com
  suffix:       issues

size:
  alt_text:          Repo Size
  service_root:      reposs.herokuapp.com
  url_path:          github.com
  # REST? Fuck REST
  ugly_cruft:        ?path=
  no_file_extension: true
